version: '3.9'

services:
  frontend:
    build: .
    image: frontend/gestionale-fe
    networks:
      - integrationai_network
    ports:
      - 4203:4203

networks:
  integrationai_network:
    external: true
 