export const LABEL_CONSTANT = {
  ricordami: "Ricordami",
  resetPassword: "Hai dimenticato la password?",
  noAccount: "Non hai un account?",
  email: "Email*",
  email_riep: "Email",
  reset_password: "Inserisci l'email per resettare la password",
  recupero_password: "Recupera la password",
  password: "Password*",
  password_riep: "Password",
  check_email: "Ti abbiamo inviato un'email in  modo da permetterti di recuperare la tua password",
  verifica_email: "Verifica la tua email",
  registrati_title: "Registrati",
  accedi: "Effettua l'accesso",
  accedi_button: "Accedi",
  inserisci_squadre: "Aggiungi i dati relativi alle squadre",
  lista_squadre:"Lista delle squadre",
  list_squadre_sub:"Questa è la lista delle squadre caricate fino ad adesso",
  lista_sponsor:"Lista degli sponsor",
  lista_sponsor_sub:"Questa è la lista degli sponsor caricati fino ad adesso",
  carica_sponsor:"Carica gli sponsor",
  squadra_casa: "Squadra di casa",
  squadra_ospite: "Squadra ospite",
  codice_gara: "Codice gara",
  data_gara: "Data gara",
  orario_gara: "Orario Gara",
  invia_dati: "Invia dati",
  punteggio: "Gestisci punteggio",
  casa: "Aggiungi casa",
  ospite: "Aggiungi ospite",
  numero_set: "Set in corso",
  possesso_palla: "Squadra in possesso di palla",
  possesso_home: "Possesso casa",
  possesso_away: "Possesso ospite",
  cambio: "Cambio possesso",
  timeout_casa: "Timeout Casa",
  timeout_ospite: "Timeout Ospite",
  timer: "Timer",
  reset_timer: "Reset timer",
  reset_punteggio: "Reset punteggio",
  secondi: "Secondi",
  set_timer: "Avvia timer",
  visualizza_nuove_schede: "Visualizza le nuove schede",
  incrementa_punteggio: "+",
  decrementa_punteggio: "-",
  ruolo: 'Ruolo',
  categoria: 'Categoria',
  squadra: 'Squadra',
  lastname: 'Cognome',
  firstname: 'Nome',
  reimposta_password: "Reimposta Password",
  insert_dati_registrazione: "Inserisci i dati richiesti per la registrazione.",
  insert_dati_reimposta_pass: "Inserisci la tua email per recuperare la password.",
  indietro: "Indietro",
  avanti: "Avanti",
  inviaEmail: "Invia Email",
  verificare_password: "verificare l'account",
  recuperare_password: "recuperare la password",
  nuova_password: "Nuova Password",
  seleziona_nuova_password: "Scegli una nuova password per accedere al tuo account.",
  link_scaduto: "Link Scaduto",
  link_non_valido: "Ci dispiace, ma questo link non è più valido.",
  carica_file: "Carica File",
  inserisci_dati_anagrafici: "Inserisci i tuoi dati anagrafici",
  email_inviata: "Email inviata correttamente",
  registrazione_completata: "Registrazione effettuata correttamente",
  credenziali: "Credenziali",
  insert_credenziali: "Inserisci la tua email d'accesso",
  insert_squadra: "Scegli squadra e categoria a cui sei associato",
  riepilogo: "Riepilogo",
  verifica_riepilogo: "Verifica i dati che hai inserito",
  insert_dati_registrazione_step_1: "Inserisci i tuoi dati anagrafici",
  dati_personali: "Inserisci i tuoi dati personali",
  errore_reg: "Errore durante la registrazione",
  add_giocatore: "Aggiungi giocatore",
  add_giocatore_fem: "Aggiungi giocatrice",
  giocatori: "Giocatori",
  giocatrici: "Giocatrici",
  partita: "Partita",
  dettaglio_giocatrici: "Dettaglio giocatrice",
  visualizza_statistiche: "Visualizza statistiche",
  dettaglio_partita: "Dettaglio partita",
  squadra_locale: "Squadra locale",
  data_orario: "Data e orario",
  parziali: "Parziali",
  nessunoSelezionato: "Nessuna selezione",
  nonSpecificato: "Non specificato",
  nome: "Nome",
  cognome: "Cognome",
  info: "E' necessario aspettare un minuto prima di effettuare un'altra richiesta",
  aggiungi_ospite: "Aggiungi ospite",
  primo_set: "Primo set",
  secondo_set: "Secondo set",
  terzo_set: "Terzo set",
  quarto_set: "Quarto set",
  quinto_set: "Quinto set",
  subtitle_punteggio: "Da questa sezione potrai accedere alla sezione dedicata alla gestione del punteggio",
  title_punteggio: "Gestisci punteggio",
  gestisci_squadra: "Gestisci la squadra",
  subtitle_squadra: "Da questa sezione potrai accedere alla sezione dedicata alla gestione della squadra",
  diretta: "Gestisci la struttura della diretta",
  subtitle_diretta: "Da questa sezione potrai gestire la maschera della diretta e i suoi relativi componenti",
  title_ledwall: "Gestione del ledwall",
  subtitle_ledwall: "Da questa sezione potrai gestire la maschera del ledwall e i suoi relativi componenti",
  giornata: "^ GIORNATA",
  serie: "SERIE",
  numero: "N. GARA:",
  femminile: "Femminile",
  maschile: "Maschile",
  visualizza_diretta: "Visualizza la struttura della diretta",
  visualizza_ledwall: "Visualizza il ledwall",
  punteggio_set: "Parziale set",
  timer_set: "Tempo effettivo set",
  timer_totale: "Tempo effettivo totale",
  title_sponsor: "Gestione sponsor",
  title_sezione_sponsor: "Gestisci i tuoi sponsor ",
  subtitle_sponsor: "Da questa sezione potrai gestire la posizione, la durata di visualizzazione degli sponsor",
  vinci: "Ha vinto",
  cartellino_rosso_casa: "Aggiungi cartellino rosso casa",
  cartellino_rosso_ospite: "Aggiungi cartellino rosso ospite",
  categoria_partita: "Serie B2", 
  girone:"Girone I",
  vs: "VS",
  title_generale: "Gestisci calendario e loghi",
  subtitle_generale: "Da questa sezione potrai gestire la struttura del ledwall,della diretta e delle squadre",
  upload_sponsor: "Carica i tuoi sponsor",
  carica_logo: "Carica logo delle squadre",
  sponsor_all:"... e altri",
  imposta_carosel:"Gestisci il carosello degli sponsor",
  intervallo:"Intervallo di visualizzazione (ms):",
  campionato:"Campionato Nazionale",
  gestione_generale: "Gestisci generalmente l'applicazione",
  rimuovi: "Rimuovi selezionati",
  carica_multipli: "Carica tutti i file",
  carica_calendario: "Carica il calendario",
  lista_calendario: "Lista dei calendari",
  lista_loghi:"Lista dei loghi delle squadre",
  subtitle_calendario: "Prima di procedere con il caricamento del caledario è necessario associare le seguenti caratteristiche al file:",
  subtitle_loghi: "Da questa sezione potrai caricare i loghi delle squadre",
  subtitle_sponsor_sub:"Da questa sezione potrai caricare gli sponsor",
  subtitle_sport: "A quale sport dobbiamo fare riferimento",
  selezione_multipla: "Seleziona tutti",
  inserisci_categoria: "Inserisci la categoria a cui fai riferimento",
  inserisci_girone: "Inserisci il girone a cui fai riferimento",
  seleziona_sport: "Seleziona lo sport",
  seleziona_girone: "Seleziona il girone",
  seleziona_squadra: "Seleziona la squadra",
  primo_set_ledwall: "SET 1°",
  secondo_set_ledwall: "SET 2°",
  terzo_set_ledwall: "SET 3°",
  quarto_set_ledwall: "SET 4°",
  quinto_set_ledwall: "SET 5°",
  seleziona_colori: "Scegli il colore che vuoi assegnare al ledwall",
  seleziona_gradiente: "Scegli il tipo di gradiente che vuoi usare",
  set: "Set",
  nessun_colore_disponibile: "Nessun colore disponibile",
  aggiungi_gradiente: "Aggiungi gradiente",
  inserisci_colore: "Inserisci colore",
  aggiungi_colore: "Aggiungi colore",
  nessun_gradiente_disponibile: "Nessun gradiente disponibile",
  inserisci_gradiente: "Inserisci il gradiente",
  cosa_vuoi_fare: "Quale attività vuoi svolgere?",
  nessun_dato: "Dati di calendario e squadre non presenti",
  lista_calendari: "Questa è la lista dei calendari caricati fino ad adesso",
  lista_loghi_sub:"Questa è la lista dei loghi caricati fino ad adesso",
  dialog_conferma_gestione: "Sei sicuro di voler gestire il punteggio per la seguente gara: ",
  tra: "tra",
  e: "e",
  winner: "Vince la squadra:"
}
