export const LABEL_CONSTANT = {
    accedi: "Accedi",
    accedi_guest:"Accedi come guest",
    inserisci_squadre:"Aggiungi i dati relativi alle squadre",
    squadra_casa:"Squadra di casa",
    squadra_ospite:"Squadra ospite",
    codice_gara:"Codice gara",
    data_gara:"Data gara",
    orario_gara:"Orario Gara",
    invia_dati:"Invia dati",
    punteggio:"Gestisci punteggio",
    casa: "Aggiungi casa",
    ospite:"Aggiungi ospite",
    numero_set:"Set in corso",
    possesso_palla:"Squadra in possesso di palla",
    possesso:"Indica possesso",
    cambio:"Cambio possesso",
    timeout_casa:"Timeout Casa",
    timeout_ospite:"Timeout Ospite",
    timer:"Timer",
    reset_timer:"Reset timer",
    reset_punteggio:"Reset punteggio",
    secondi:"Secondi",
    set_timer:"Avvia timer",
    visualizza_nuove_schede:"Visualizza le nuove schede",
    aggiungi_casa:"Aggiungi casa",
    aggiungi_ospite:"Aggiungi ospite",
    primo_set:"Primo set",
    secondo_set:"Secondo set",
    terzo_set:"Terzo set",
    quarto_set:"Quarto set",
    quinto_set:"Quinto set",
    subtitle_punteggio:"Da questa sezione potrai accedere alla sezione dedicata alla gestione del punteggio",
    title_punteggio:"Gestisci punteggio",
    gestisci_squadra:"Gestisci la squadra",
    subtitle_squadra:"Da questa sezione potrai accedere alla sezione dedicata alla gestione della squadra",
    diretta:"Gestisci la struttura della diretta",
    subtitle_diretta:"Da questa sezione potrai gestire la maschera della diretta e i suoi relativi componenti",
    title_ledwall:"Gestione del ledwall",
    subtitle_ledwall:"Da questa sezione potrai gestire la maschera del ledwall e i suoi relativi componenti",
    giornata:"^ GIORNATA",
    serie:"SERIE",
    numero:"N. GARA:",
    femminile:"FEMMINILE",
    maschile:"MASCHILE",
    visualizza_diretta:"Visualizza la struttura della diretta",
    visualizza_ledwall: "Visualizza il ledwall",
    punteggio_set:"Parziale set",
    timer_set:"Tempo effettivo set",
    timer_totale:"Tempo effettivo totale",
    title_sponsor:"Gestione sponsor",
    title_sezione_sponsor:"Gestisci i tuoi sponsor ",
    subtitle_sponsor:"Da questa sezione potrai gestire la posizione, la durata di visualizzazione degli sponsor",
    vinci:"Ha vinto",
    cartellino_rosso_casa:"Aggiungi cartellino rosso casa",
    cartellino_rosso_ospite:"Aggiungi cartellino rosso ospite",
    categoria:"SERIE B2/I",
    vs:"VS",
    title_generale:"Gestisci calendario e loghi",
    subtitle_generale:"Da questa sezione potrai gestire la struttura del ledwall,della diretta e delle squadre",
    upload_sponsor:"Carica i tuoi sponsor",
    carica_logo:"Carica i loghi delle squadre",
    gestione_generale:"Gestisci generalmente l'applicazione",
    rimuovi:"Rimuovi selezionati",
    carica_multipli:"Carica tutti i file",
    carica_calendario:"Carica il calendario",
    lista_calendario:"Lista dei calendari",
    subtitle_calendario:"Prima di procedere con il caricamento del caledario è necessario associare le seguenti caratteristiche al file:",
    subtitle_loghi:"Da questa sezione potrai caricare i loghi delle squadre",
    subtitle_sport:"A quale sport dobbiamo fare riferimento",
    selezione_multipla:"Seleziona tutti",
    inserisci_categoria:"Inserisci la categoria a cui fai riferimento",
    inserisci_girone:"Inserisci il girone a cui fai riferimento",
    seleziona_sport:"Seleziona lo sport",
    seleziona_girone:"Seleziona il girone",
    seleziona_squadra:"Seleziona la squadra",
    primo_set_ledwall:"SET 1°",
    secondo_set_ledwall:"SET 2°",
    terzo_set_ledwall:"SET 3°",
    quarto_set_ledwall:"SET 4°",
    quinto_set_ledwall:"SET 5°",
    seleziona_colori:"Scegli il colore che vuoi assegnare al ledwall",
    seleziona_gradiente:"Scegli il tipo di gradiente che vuoi usare",
    set:"Set",
    nessun_colore_disponibile:"Nessun colore disponibile",
    aggiungi_gradiente:"Aggiungi gradiente",
    inserisci_colore:"Inserisci colore",
    aggiungi_colore:"Aggiungi colore",
    nessun_gradiente_disponibile:"Nessun gradiente disponibile",
    inserisci_gradiente:"Inserisci il gradiente",
    cosa_vuoi_fare:"Quale attività vuoi svolgere?",
    nessun_dato:"Dati di calendario e squadre non presenti",
    lista_calendari:"Questa è la lista dei calendari caricati fino ad adesso",
    dialog_conferma_gestione:"Sei sicuro di voler gestire il punteggio per la gara :",
    tra:"tra",
    e:"e",
  }
  